### ISSUE TITLE
Jenkins' SIGINT handling not being invoked

### ISSUE THREAD

**Issue by rtyler** [rtyler/vagrant-plugin#14]
After the first Vagrant-baesd job runs inside of Jenkins, the SIGINT/SIGTERM handling gets obliterated, requiring a SIGKILL to stop the server.

This sucks.

**Comment by rtyler** [comment]
Vagrant will trap `SIGINT` and then resets the SIGINT handler to 'DEFAULT' ([busy.rb#L43](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/busy.rb#L42)) which _may_ be clearing Jenkins' handler as well.

**Comment by rtyler** [comment]
Discussed this with @kohsuke on IRC, looks like the JRuby implementation of the `Signal` class doesn't properly support the resetting of a handler to 'DEFAULT'. 

Working on a patch to the forked Vagrant we're using that calls the Java APIs for doing so instead.

![](http://thechive.files.wordpress.com/2012/02/82300927.gif?w=230&h=145)

**Comment by kohsuke** [comment]
Created https://github.com/jruby/jruby/pull/128 to fix this in JRuby.
