### ISSUE TITLE
FATAL: java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1InputStream.readObject()

### ISSUE THREAD

**Issue by saimonmoore** [rtyler/vagrant-plugin#26]
Hi,

I've been trying to configure the vagrant plugin but I keep running into some openssl issue:

https://gist.github.com/e614e987f111d5e82650

My Vagrant file:

https://gist.github.com/fd4843af9097cc48179d

I'm running:
- Jenkins ver. 1.491
- 0.10 of the ruby runtime plugin
- 0.1.4 of the vagrant plugin

I'm a bit stuck at this point. Any help is appreciated.

**Comment by tindron** [comment]
I ran into the same issue and ended up downgrading my jenkins to 1.487 to get the plugin working again.

**Comment by saimonmoore** [comment]
Unfortunately, that's not a possibility in my case. :(

**Comment by otetard** [comment]
I have the same problem with Jenkins 1.492 on a Debian Wheezy system (up to date, as of today).

Downgrading to Jenkins 1.487, as suggested by @tindron, fixed the problem for me.

**Comment by jimi-c** [comment]
I kept using "yum downgrade jenkins" until it worked, which for me was 1.489-1:

<pre>
Removed:
  jenkins.noarch 0:1.490-1.1
Installed:
  jenkins.noarch 0:1.489-1.1 
</pre>

**Comment by axelson** [comment]
If you're on Ubuntu you can easily install 1.487 by downloading it from here:

http://pkg.jenkins-ci.org/debian/

**Comment by riuvshin** [comment]
what i need to do to solve such error ?
FATAL: org.bouncycastle.asn1.ASN1InputStream.readObject()Lorg/bouncycastle/asn1/DERObject;

@tpodom  Your commit should fix that bug? how to update?

**Comment by tpodom** [comment]
@riuvshin See my instructions in https://github.com/rtyler/vagrant-plugin/pull/32 for how to update using the versions I've built.

**Comment by ghost** [comment]
@tpodom Thank you!

**Comment by poflynn** [comment]
This issue is listed as a "Major Known Issue" on the plug-ins homepage (https://wiki.jenkins-ci.org/display/JENKINS/Vagrant+Plugin). Is this mistaken and in fact it is fixed and works fine on newer versions of Jenkins? Thanks.
