### ISSUE TITLE
Relative Vagrantfile Path Not Working

### ISSUE THREAD

**Issue by jessebs** [rtyler/vagrant-plugin#42]
Under the Boot Up Vagrant VM task, specifying a relative path to the Vagrantfile doesnt work.

Tried: 
./Vagrantfile and Vagrantfile

It appears as though 'vagrant up' tries to execute in /

I can fix this by using the full path (/var/lib/jenkins/jobs/project/workspace/Vagrantfile), but it's not ideal

**Comment by toejough** [comment]
Why was this closed?  I'm having the same issue - could you explain how you worked around this?

**Comment by toejough** [comment]
If anyone else checks this out, I found it easier to just use exec steps to do everything, rather than using this plugin.

**Comment by neilhwatson** [comment]
I found the same problem. This issue should be fixed.
